ports:
- port: 3000

tasks:
  - init: |
      corepack enable
      corepack prepare yarn@stable --activate
      yarn --cwd website
      yarn --cwd website compile
      yarn --cwd website build
      yarn --cwd website build:dev
    command: |
      cd website
      yarn start:dev
              - name: Satellite file upload
                uses: IBM/satellite-config-upload-action@v1.0.1
            
