name: Claim namespace ownership
description: Request exclusive publishing rights to an Open VSX namespace
title: "Claiming namespace [name]"
labels: ["namespace", "operations"]
assignees:
  - kineticsquid
body:
  - type: markdown
    attributes:
      value: |
        Our objective with the **Open VSX** Namespace approval process is to provide an open and transparent process
        and set of records (issues) to document requests, processing and approval of **Open VSX** namespace ownership.

        A further goal is ensure the publishers and extensions are legitimate, do not misrepresent themselves and do
        not introduce confusion between extensions published on the VS Code Marketplace and the **Open VSX** Registry.

        To those ends, please place check marks on the following items that apply to your request and provide the
        requested information. If you fail to do so, your request will not be approved.
  - type: input
    id: namespace
    attributes:
      label: Namespace
    validations:
      required: true
  - type: checkboxes
    id: ownership
    attributes:
      label: Ownership
      options:
        - label: The namespace is not currently owned on Open VSX (verify by a search on [open-vsx.org](https://open-vsx.org))
          required: false
  - type: checkboxes
    id: account-age
    attributes:
      label: Account Age
      options:
        - label: The GitHub ID making this request has at least 12 months of public history
          required: false
  - type: textarea
    attributes:
      label: Claim evidence
      value: |
        ### Chose one of the following four use cases and respond to the items
        - [ ] __1__ - The namespace is also a publisher account on the VS Code Marketplace (check by browsing https://marketplace.visualstudio.com/publishers/{publisher}) and has an extension published there.
            - [ ] The extension repo is a GitHub repo and is specified and public
                - [ ] The extension repo is owned by the GitHub ID making this request (same org)
                - [ ] If not, provide the URL of a commit in the extension repo by the GitHub ID making this request
                    - {URL}
        - [ ] __2__ - The namespace is also a publisher account on the VS Code Marketplace and does not have published extensions or has published extensions with no repos listed or only private repos listed.  Do one of the following:
            - [ ] Provide Open VSX administrator ID (`9f9ebf84-37d2-648b-bef8-8af4132d803a`) temporary reader access to the VS Code Marketplace Publisher Account. (Be sure to revoke the reader permission once request has closed)
            - [ ] If the namespace matches your domain name, define a TXT record in your DNS, listing the URL to this issue and provide the domain/subdomain
              - {domain/subdomain}
            - [ ] If the namespace matches your domain name, send an email to [openvsx@eclipse-foundation.org](mailto:openvsx@eclipse-foundation.org) from an email account with a domain name that matches the namespace
              - {email domain/subdomain}
        - [ ] __3__ - The namespace is not a publisher account on the VS Code Marketplace
            - [ ] The namespace matches the GitHub ID making this request
            - [ ] The namespace does not match the GitHub ID making this request. Do one of the following:
                - [ ] If the namespace matches your domain name, define a TXT record in your DNS listing the URL to this issue and provide the domain/subdomain
                    - {domain/subdomain}
                - [ ] If the namespace matches your domain name, send an email to [openvsx@eclipse-foundation.org](mailto:openvsx@eclipse-foundation.org) from an email account with a domain name that matches the namespace
                    - {email domain/subdomain}
        - [ ] __4__ - Otherwise provide a justification for granting ownership of the namespace (this type of request will take the longest to process)
            - {justification}
