{
 "title": "Tracing",
 "description": "Trace overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes,environment)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{environment=~\"$environment\"},application)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{environment=~\"$environment\", application=~\"$application\"},instance)"
    }
   },
   { "name": "traceId", "label": "Trace ID" }
  ]
 },
 "panels": [
  {
   "title": "Slow Requests (> 1s)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "cef8ff62", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "openvsx-server" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "1s",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "query": "{resource.deployment.environment=\"${environment}\" && resource.service.instance.id=\"${instance}\" && resource.service.name=\"${application}\" && duration>1s}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Trace Overview",
   "type": "traces",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "limit": 20, "query": "${traceId}", "tableType": "traces" }
   ]
  },
  {
   "title": "Trace Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{traceID=\"$traceId\"} |= ``"
    }
   ]
  }
 ]
}