apiVersion: v1
kind: ConfigMap
metadata:
  name: application-configuration-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
data:
  application.yml: |
{{ .Values.applicationConfig | indent 4 }}
