{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: postgresql-{{ .Values.environment }}-hpa
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    # Matches your 'staging-postgresql-ha-postgresql' naming logic
    name: {{ .Values.environment }}-postgresql-ha-postgresql
  minReplicas: 3
  maxReplicas: 9
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
{{- end }}
