{{- if .Values.eks.enabled }}
{{- $preActions := .Values.ingress.preActions | default (list "ssl-redirect") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "alb" }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      {{- range $action := $preActions }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $action }}
            port:
              name: use-annotation
      {{- end }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}-{{ .Values.environment }}
            port:
              number: {{ .Values.service.port }}
{{- if eq .Values.environment "production" }}
  - host: www.{{ .Values.host }}
    http:
      paths:
      {{- range $action := $preActions }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $action }}
            port:
              name: use-annotation
      {{- end }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}-{{ .Values.environment }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
{{- end }}
