{{- if and .Values.eks.enabled .Values.serviceMonitors.platformMetrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics-monitor
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
spec:
  namespaceSelector:
    matchNames:
      - kube-state-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  endpoints:
    - path: /metrics
      interval: 60s
      targetPort: 8080
{{- end }}
