{{- if and .Values.eks.enabled .Values.serviceMonitors.platformMetrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter-monitor
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
spec:
  namespaceSelector:
    matchNames:
      - prometheus-node-exporter
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-node-exporter
  endpoints:
    - path: /metrics
      interval: 60s
      targetPort: 9100
{{- end }}
