apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
  name: spring-boot-monitor-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
      environment: {{ .Values.environment }}
      type: website
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: 60s