# Default values for openvsx eks staging.

name: &name open-vsx-org
environment: &environment staging
namespace: &namespace open-vsx-org-staging
host: eks-staging.open-vsx.org

replicaCount: 1
esReplicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

image:
  repository: ghcr.io/eclipsefdn/openvsx-website
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 6d777ca-570

eks:
  enabled: true  # Switch to false for OKD installations

aws-load-balancer-controller:
  clusterName: eks-staging
  region: eu-central-1
  vpcId: vpc-0285cbfe9bfb7e4fd
  serviceAccount:
    create: false
    name: aws-load-balancer-controller-staging

external-dns:
  provider:
    name: aws
  serviceAccount:
    create: false
    name: external-dns-staging
  txtOwnerId: eks-staging
  extraArgs:
    - --source=ingress
    - --aws-zone-type=public
    - --domain-filter=open-vsx.org

ingress:
  certArn: arn:aws:acm:eu-central-1:365555376529:certificate/c247a8c7-31fa-4116-bd4a-c1e5aebad840

website:
  jvmArgs: >
    -Xms4G -Xmx6G
    -XX:+AlwaysPreTouch
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+UseStringDeduplication
    -XX:+ParallelRefProcEnabled
    -XX:+DisableExplicitGC
    -XX:+UnlockExperimentalVMOptions
    -XX:+UnlockDiagnosticVMOptions
    -Dlog4j2.formatMsgNoLookups=true
    -Dlog4j.formatMsgNoLookups=true
    -Dorg.jooq.no-logo=true
    -Dorg.jooq.no-tips=true
    --enable-native-access=ALL-UNNAMED

route:
  timeout: 30s

resources:
  limits:
    cpu: 5000m
    memory: 8Gi
  requests:
    cpu: 3000m
    memory: 8Gi

# elastic search
es:
  commonAnnotations:
    "karpenter.sh/do-not-disrupt": "true"
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"

  pdb:
    create: true
    minAvailable: 1
  
  java_opts: -Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 2Gi
  storage_class: gp3

postgresql-ha:
  pgpool:
    enabled: false
  postgresql:
    metrics:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      serviceMonitor:
        enabled: true
        interval: 30s
        labels:
          app: open-vsx-org
          environment: staging
    image:
      repository: bitnamilegacy/postgresql-repmgr
      tag: 17.6.0-debian-12-r2
    database: openvsx-staging
    createDatabase: true
    username: "openvsx-staging-rw"
    enablePostgresUser: true
    extraEnvVars:
      - name: POSTGRESQL_SR_CHECK_PASSWORD
    auth:
      passwordEncryption: "scram-sha-256"
    authenticationConfiguration: |
      host all all 0.0.0.0/0 scram-sha-256
      local all all peer
    extendedConf: |-
      max_connections = 250
      # Optimized for 2Gi RAM (25% rule)
      shared_buffers = 1024MB
      # Memory per-query (safe for 100 connections)
      work_mem = 4MB   
      maintenance_work_mem = 128MB
      # Helps the query planner understand 2Gi RAM
      effective_cache_size = 3000MB
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"   
        memory: "4Gi"
    pdb:
      create: true
      minAvailable: 1
    podAnnotations:
      "karpenter.sh/do-not-disrupt": "true"
      "cluster-autoscaler.kubernetes.io/safe-to-evict": "false" 

# redis
redis:
  master:
    pdb:
      create: true
      minAvailable: 1
    podAnnotations:
      "karpenter.sh/do-not-disrupt": "true"
      "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
  replica:
    pdb:
      create: true
      minAvailable: 1
    podAnnotations:
      "karpenter.sh/do-not-disrupt": "true"
      "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"

  maxmemory: "256mb"
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "100m"
  persistence:
    storageGi: 1
    storageClass: "gp3"
  serviceAccountName: redis-cluster-operator-staging
  clusterRoleName: redis-cluster-operator-role-cluster-staging
  clusterRoleBindingName:  redis-cluster-operator-role-binding-cluster-staging
  roleName: redis-cluster-operator-role-staging
  roleBinding: redis-cluster-operator-role-binding-staging

# grafana alloy
alloy:
  alloy:
    configMap:
      create: false
      name: "grafana-alloy-configmap-staging"
      key: "config.river"
    envFrom:
      - secretRef: 
          name: grafana-cloud-secret-staging
      - secretRef: 
          name: redis-secret-staging
  crds:
    create: true
  controller:
    type: "daemonset"
    podLabels:
      app: *name
      environment: *environment
    nodeSelector:
      openvsx-production-alloy: null
  fullnameOverride: grafana-alloy-staging
  namespaceOverride: *namespace

clamav:
  enabled: false

yara:
  enabled: false