name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: none

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get all changed website files
        id: changed_website_files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: website/**

      - name: Set up Node.js
        if: steps.changed_website_files.outputs.any_changed == 'true'
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.x

      - name: Install Yarn
        if: steps.changed_website_files.outputs.any_changed == 'true'
        working-directory: website
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Build Website
        if: steps.changed_website_files.outputs.any_changed == 'true'
        working-directory: website
        run: |
          yarn install --immutable
          yarn build

  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.x

      - name: Install Yarn
        working-directory: website
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn install --immutable

      - uses: j178/prek-action@cbc2f23eb5539cf20d82d1aabd0d0ecbcc56f4e3 # v2.0.2
