name: Build
on:
  push:
    branches:
      - aws-main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: none

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Get all changed website files
        id: changed_website_files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: website/**

      - name: Set up Node.js
        if: steps.changed_website_files.outputs.any_changed == 'true'
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.x

      - name: Install Yarn
        if: steps.changed_website_files.outputs.any_changed == 'true'
        working-directory: website
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Build Website
        if: steps.changed_website_files.outputs.any_changed == 'true'
        working-directory: website
        run: |
          yarn install --immutable
          yarn build

  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.x

      - name: Install Yarn
        working-directory: website
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn install --immutable

      - uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
