name: Sonar
on:
  push:
    branches:
      - master

permissions:
  contents: none

jobs:
  sonar:
    name: Sonar
    runs-on: ubuntu-latest
    if: github.repository == 'EclipseFdn/open-vsx.org'
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
          persist-credentials: false
          fetch-depth: 0
    - name: Cache SonarCloud packages
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e  # v8.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
